language: python
python:
  - "3.8"
before_install:
    - python -m pip install --upgrade pip wheel
    - choco install sqlite --version 3.21.0
install:
  - pip install -r requirements.txt
  - python manage.py migrate
script:
  - black --check blogging polling mysite
  - python manage.py test blogging