language: python
python:
  - "3.7"
before_install:
    - python -m pip install --upgrade pip wheel
install:
  - pip install -r ./mysite/requirements.txt
  - python ./mysite/manage.py migrate
script:
  - black --check blogging polling mysite
  - python ./mysite/manage.py test blogging